Integration specs for views
kingqabil/Blog-App pull request #12
Opened 2022-04-22 18:30 UTC by kingqabil

- Used Capybara to write integration tests for each view in your project.
- Login page:
1. I can see the username and password inputs and the "Submit" button.
2. When I click the submit button without filling in the username and the password, I get a detailed error.
3. When I click the submit button after filling in the username and the password with incorrect data, I get a detailed error.
4. When I click the submit button after filling in the username and the password with correct data, I am redirected to the root page.
- User index page:
1. I can see the username of all other users.
2. I can see the profile picture for each user.
3. I can see the number of posts each user has written.
4. When I click on a user, I am redirected to that user's show page.
5. User show page:
6. I can see the user's profile picture.
7. I can see the user's username.
8. I can see the number of posts the user has written.
9. I can see the user's bio.
10. I can see the user's first 3 posts.
11. I can see a button that lets me view all of a user's posts.
12. When I click a user's post, it redirects me to that post's show page.
13. When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
1. I can see the user's profile picture.
2. I can see the user's username.
3. I can see the number of posts the user has written.
4. I can see a post's title.
5. I can see some of the post's body.
6. I can see the first comments on a post.
7. I can see how many comments a post has.
8. I can see how many likes a post has.
9. I can see a section for pagination if there are more posts than fit on the view.
10. When I click on a post, it redirects me to that post's show page.
- Post show page:
1. I can see the post's title.
2. I can see who wrote the post.
3. I can see how many comments it has.
4. I can see how many likes it has.
5. I can see the post body.
6. I can see the username of each commentor.
7. I can see the comment each commentor left.

2022-04-22 22:59 UTC, Gambit142 requested changes
Hi @kingqabil 👋 @AtillaTahak 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Great work writing most of the tests required for this milestone. 👍 

## Required Changes ♻️

- The first required change would be to remove one `end` statement in the migration file that creates likes. This prevents you from creating the tables that would be used in the database.

This is what you have:
```
class CreateLikes < ActiveRecord::Migration[7.0]
  def change
    create_table :likes, &:timestamps
    end
  end
end

```

- _Kindly check the comments under the review for other suggested changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider implementing the optional changes suggested under the review. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-22 22:59 UTC, Gambit142 commented on spec/views/session_spec.rb
> +      visit new_user_session_path
- [ ] (Optional) The subject of this test case should reflect that the wrong user login details were filled. Having descriptions that are easy to understand makes it easier for other programmers to know what you are trying to achieve in a test. 👍

2022-04-22 22:59 UTC, Gambit142 commented on spec/views/user_show_page_spec.rb
> +end
- [ ] (Required) Great work writing tests that are required. Kindly add a test that redirects to the post's show page when you click on a user's post. 👍

2022-04-22 22:59 UTC, Gambit142 commented on spec/views/post_index_page_spec.rb
> +    end
- [ ] (Optional) It would be a more precise test to expect the `post.comments_counter` to equal a number

2022-04-22 22:59 UTC, Gambit142 commented on spec/views/post_index_page_spec.rb
> +    end
- [ ] (Optional) It would be a more precise test to expect the `post.likes_counter` to equal a number

2022-04-22 22:59 UTC, Gambit142 commented on spec/views/post_index_page_spec.rb
> +end
- [ ] (Required) Kindly add tests that assert you can see a section for pagination if there are more posts than fit on the view.

2022-04-22 22:59 UTC, Gambit142 commented on spec/views/post_show_page_spec.rb
> +    end
- [ ] (Optional) It would be a more precise test to check if you can see the name of the commenter. 👍

2022-04-23 11:34 UTC, DeliceLydia approved these changes
## Hi @kingqabil, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### You Rock!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 11:40 UTC, merged